-- generated by csdl-to-sql for target h2 from metadata.csdl.xml

create sequence "mahlwerkNew_AddressSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_AddressSet_1_0"
(
    "AddressID" bigint not null,
    "Country" varchar(320) not null,
    "HouseNumber" varchar(320) not null,
    "PostalCode" varchar(320) not null,
    "Street" varchar(320) not null,
    "Town" varchar(320) not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("AddressID")
);

create index "mahlwerkNew_AddressSet_1_0_last_modified_index" on "mahlwerkNew_AddressSet_1_0" ("last_modified");

create sequence "mahlwerkNew_MaterialPositionSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_MaterialPositionSet_1_0"
(
    "JobID" bigint not null,
    "MaterialID" bigint not null,
    "MaterialPositionID" bigint not null,
    "Quantity" smallint not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("MaterialPositionID")
);

create index "mahlwerkNew_MaterialPositionSet_1_0_last_modified_index" on "mahlwerkNew_MaterialPositionSet_1_0" ("last_modified");

create sequence "mahlwerkNew_xs_data_metrics_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_xs_data_metrics_1_0"
(
    "id" bigint not null,
    "start" timestamp not null,
    "period" decimal(20,6) not null,
    "process" varchar(400) not null,
    "provider" varchar(400) not null,
    "component" varchar(800) not null,
    "metric" varchar(400) not null,
    "unit" varchar(200) not null,
    "count" bigint null,
    "sum" bigint null,
    "average" decimal(25,2) null,
    "minimum" bigint null,
    "maximum" bigint null,
    primary key ("id")
);

create sequence "mahlwerkNew_OrderSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_OrderSet_1_0"
(
    "CustomerID" bigint not null,
    "Description" varchar(1024) null,
    "DueDate" date not null,
    "OrderID" bigint not null,
    "OrderStatusID" bigint not null,
    "Title" varchar(320) not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("OrderID")
);

create index "mahlwerkNew_OrderSet_1_0_last_modified_index" on "mahlwerkNew_OrderSet_1_0" ("last_modified");

create table "mahlwerkNew_xs_request_history_1_0"
(
    "CreationTime" timestamp not null,
    "ResponseStatus" smallint not null,
    "ClientID" varbinary(100) not null,
    "RequestID" varbinary(100) not null,
    "ResponseHeaders" varchar(4000) not null,
    "ResponseData1" varbinary(2000) null,
    "ResponseData2" blob null,
    primary key ("ClientID", "RequestID")
);

create index "mahlwerkNew_xs_request_history_1_0_creation_time_index" on "mahlwerkNew_xs_request_history_1_0" ("CreationTime");

create sequence "mahlwerkNew_PartSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_PartSet_1_0"
(
    "Name" varchar(2000) not null,
    "PartID" bigint not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("PartID")
);

create index "mahlwerkNew_PartSet_1_0_last_modified_index" on "mahlwerkNew_PartSet_1_0" ("last_modified");

create sequence "mahlwerkNew_PartsToChangeSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_PartsToChangeSet_1_0"
(
    "JobID" bigint not null,
    "PartID" bigint not null,
    "PartsToChangeID" bigint not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("PartsToChangeID")
);

create index "mahlwerkNew_PartsToChangeSet_1_0_last_modified_index" on "mahlwerkNew_PartsToChangeSet_1_0" ("last_modified");

create sequence "mahlwerkNew_MachineColorsSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_MachineColorsSet_1_0"
(
    "MachineColorsID" bigint not null,
    "MachineID" bigint not null,
    "colorName" varchar(2000) not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    "media" blob null,
    "media_etag" varchar(200) null,
    "media_type" varchar(600) null,
    primary key ("MachineColorsID")
);

create index "mahlwerkNew_MachineColorsSet_1_0_last_modified_index" on "mahlwerkNew_MachineColorsSet_1_0" ("last_modified");

create sequence "mahlwerkNew_UserSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_UserSet_1_0"
(
    "Email" varchar(320) not null,
    "FirstNames" varchar(320) not null,
    "LastNames" varchar(320) not null,
    "Phone" varchar(320) not null,
    "UserID" bigint not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("UserID")
);

create index "mahlwerkNew_UserSet_1_0_last_modified_index" on "mahlwerkNew_UserSet_1_0" ("last_modified");

create sequence "mahlwerkNew_ToolPositionSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_ToolPositionSet_1_0"
(
    "JobID" bigint not null,
    "Quantity" smallint not null,
    "ToolID" bigint not null,
    "ToolPositionID" bigint not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("ToolPositionID")
);

create index "mahlwerkNew_ToolPositionSet_1_0_last_modified_index" on "mahlwerkNew_ToolPositionSet_1_0" ("last_modified");

create sequence "mahlwerkNew_JobSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_JobSet_1_0"
(
    "ActualWorkHours" smallint null,
    "DoneDate" timestamp null,
    "JobID" bigint not null,
    "JobStatusID" bigint not null,
    "PredictedWorkHours" smallint not null,
    "Suggested" tinyint not null,
    "TaskID" bigint not null,
    "Title" varchar(320) not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("JobID")
);

create index "mahlwerkNew_JobSet_1_0_last_modified_index" on "mahlwerkNew_JobSet_1_0" ("last_modified");

create sequence "mahlwerkNew_ToolSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_ToolSet_1_0"
(
    "Name" varchar(320) not null,
    "ToolID" bigint not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("ToolID")
);

create index "mahlwerkNew_ToolSet_1_0_last_modified_index" on "mahlwerkNew_ToolSet_1_0" ("last_modified");

create sequence "mahlwerkNew_OrderEventsSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_OrderEventsSet_1_0"
(
    "Date" date not null,
    "OrderEventTypeID" bigint not null,
    "OrderEventsID" bigint not null,
    "OrderID" bigint not null,
    "Text" varchar(2048) null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("OrderEventsID")
);

create index "mahlwerkNew_OrderEventsSet_1_0_last_modified_index" on "mahlwerkNew_OrderEventsSet_1_0" ("last_modified");

create sequence "mahlwerkNew_StepSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_StepSet_1_0"
(
    "JobID" bigint not null,
    "Name" varchar(320) not null,
    "StepID" bigint not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("StepID")
);

create index "mahlwerkNew_StepSet_1_0_last_modified_index" on "mahlwerkNew_StepSet_1_0" ("last_modified");

create sequence "mahlwerkNew_MachineConfigurationSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_MachineConfigurationSet_1_0"
(
    "MachineColorsID" bigint not null,
    "MachineConfigurationID" bigint not null,
    "MachineID" bigint not null,
    "OrderID" bigint not null,
    "Pressure" varchar(2000) null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("MachineConfigurationID")
);

create index "mahlwerkNew_MachineConfigurationSet_1_0_last_modified_index" on "mahlwerkNew_MachineConfigurationSet_1_0" ("last_modified");

create sequence "mahlwerkNew_MaterialSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_MaterialSet_1_0"
(
    "MaterialID" bigint not null,
    "Name" varchar(320) not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("MaterialID")
);

create index "mahlwerkNew_MaterialSet_1_0_last_modified_index" on "mahlwerkNew_MaterialSet_1_0" ("last_modified");

create sequence "mahlwerkNew_CustomerSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_CustomerSet_1_0"
(
    "AddressID" bigint not null,
    "CompanyName" varchar(320) not null,
    "CustomerID" bigint not null,
    "Email" varchar(320) not null,
    "Name" varchar(320) not null,
    "Phone" varchar(320) not null,
    "TaskID" bigint not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("CustomerID")
);

create index "mahlwerkNew_CustomerSet_1_0_last_modified_index" on "mahlwerkNew_CustomerSet_1_0" ("last_modified");

create sequence "mahlwerkNew_TaskSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_TaskSet_1_0"
(
    "AddressID" bigint not null,
    "CustomerID" bigint not null,
    "FinalReportStatusID" bigint not null,
    "MachineID" bigint not null,
    "Notes" varchar(2048) null,
    "OrderID" bigint not null,
    "ScheduledDate" date null,
    "TaskID" bigint not null,
    "TaskStatusID" bigint not null,
    "Title" varchar(320) not null,
    "UserID" bigint not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    primary key ("TaskID")
);

create index "mahlwerkNew_TaskSet_1_0_last_modified_index" on "mahlwerkNew_TaskSet_1_0" ("last_modified");

create sequence "mahlwerkNew_MachineSet_1_0_id_seq" start with 1 increment by 1 nocache;

create table "mahlwerkNew_MachineSet_1_0"
(
    "Description" varchar(1024) not null,
    "MachineID" bigint not null,
    "Name" varchar(320) not null,
    "row_version" bigint not null,
    "is_deleted" tinyint not null,
    "last_modified" timestamp not null,
    "media" blob null,
    "media_etag" varchar(200) null,
    "media_type" varchar(600) null,
    primary key ("MachineID")
);

create index "mahlwerkNew_MachineSet_1_0_last_modified_index" on "mahlwerkNew_MachineSet_1_0" ("last_modified");
