{
	"Animated": true,
	"CompletionTimeout": 3,
	"Message": "Checking for Updates...",
	"OnSuccess": "/Mahlwerk_Sales/Actions/Application/AppUpdateCheck.action",
	"_Type": "Action.Type.ProgressBanner"
}