source 'https://github.com/SAP-samples/cloud-sdk-ios-specs'

platform :ios, '15.0'
use_frameworks!

target 'Mahlwerk' do
  pod 'SAPCommon', '~> 9.0'
  pod 'SAPFoundation', '~> 9.0'
  pod 'SAPFiori', '~> 9.0'
  pod 'SAPFioriFlows', '~> 9.0'
  pod 'SAPOfflineOData', '~> 9.0'
  pod 'SAPOData', '~> 9.0'
end
