source 'https://github.com/SAP-samples/cloud-sdk-ios-specs'

platform :ios, '14.0'
use_frameworks!

target 'Mahlwerk' do
  pod 'SAPCommon', '~> 6.1'
  pod 'SAPFoundation', '~> 6.1'
  pod 'SAPFiori', '~> 6.1'
  pod 'SAPFioriFlows', '~> 6.1'
  pod 'SAPOfflineOData', '~> 6.1'
  pod 'SAPOData', '~> 6.1'
end
