{
	"ActionResult": {
		"_Name": "CreateCustomer"
	},
	"OnFailure": "/Mahlwerk_Sales/Actions/CustomerSet/CreateNewCustomerFails.action",
	"OnSuccess": "/Mahlwerk_Sales/Actions/CloseModalPage_Complete.action",
	"Properties": {
		"CompanyName": "#Page:CreateNewCustomer/#Control:FormCellSimplePropertyCN/#Value",
		"Email": "#Page:CreateNewCustomer/#Control:FormCellSimplePropertyEM/#Value",
		"Name": "#Page:CreateNewCustomer/#Control:FormCellSimplePropertyAP/#Value",
		"Phone": "#Page:CreateNewCustomer/#Control:FormCellSimplePropertyTN/#Value"
	},
	"Target": {
		"EntitySet": "CustomerSet",
		"Service": "/Mahlwerk_Sales/Services/Mahlwerk_Sales_MDK.service"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}