{
	"ActionResult": {
		"_Name": "DeleteORDER"
	},
	"OnFailure": "/Mahlwerk_Sales/Actions/CustomerSet/DeleteOrderFails.action",
	"OnSuccess": "/Mahlwerk_Sales/Actions/CustomerSet/DeleteCustomerEntity.action",
	"Target": {
		"EntitySet": "OrderSet",
		"QueryOptions": "$filter=CustomerID eq {{#Control:SectionKeyValue0/#Value}}",
		"Service": "/Mahlwerk_Sales/Services/Mahlwerk_Sales_MDK.service"
	},
	"_Type": "Action.Type.ODataService.DeleteEntity"
}