{
	"ActionResult": {
		"_Name": "DeleteCUST"
	},
	"OnFailure": "/Mahlwerk_Sales/Actions/CustomerSet/DeleteCustomerFails.action",
	"OnSuccess": "/Mahlwerk_Sales/Actions/CloseModalPage_Complete.action",
	"Target": {
		"EntitySet": "CustomerSet",
		"QueryOptions": "$filter=CustomerID eq {{#Control:SectionKeyValue0/#Value}}",
		
		"Service": "/Mahlwerk_Sales/Services/Mahlwerk_Sales_MDK.service"
	},
	"_Type": "Action.Type.ODataService.DeleteEntity"
}