{
	"ActionResult": {
		"_Name": "DeleteCONFIG"
	},
	"OnFailure": "/Mahlwerk_Sales/Actions/CustomerSet/DeleteConfigurationFails.action",
	"OnSuccess": "/Mahlwerk_Sales/Actions/CustomerSet/DeleteOrderEntity.action",
	"Target": {
		"EntitySet": "MachineConfigurationSet",
		"QueryOptions": "$expand=Order, Order/Customer&$filter=Order/CustomerID eq {{#Control:SectionKeyValue0/#Value}}",
		"Service": "/Mahlwerk_Sales/Services/Mahlwerk_Sales_MDK.service"
	},
	"_Type": "Action.Type.ODataService.DeleteEntity"
}