{
	"ActionResult": {
		"_Name": "CreateOrder"
	},
	"CreateLinks": [
		{
			"Property": "Customer",
			"Target": {
				"EntitySet": "CustomerSet",
				"QueryOptions": "$filter=CustomerID eq {#Control:FormCellListPicker0/#SelectedValue}"
			},
			"_Enabled": true
		}
	],
	"OnFailure": "/Mahlwerk_Sales/Actions/CreateOrderFails.action",
	"OnSuccess": "/Mahlwerk_Sales/Actions/CreateNewConfigEntity.action",
	"Properties": {
		"CustomerID": "#Control:FormCellListPicker0/#SelectedValue",
		"Description": "New Order",
		"DueDate": "#Control:FormCellDatePicker0/#Value",
		"OrderStatusID": 2,
		"Title": "New Order"
	},
	"Target": {
		"EntitySet": "OrderSet",
		"Service": "/Mahlwerk_Sales/Services/Mahlwerk_Sales_MDK.service"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}