{
	"ActionResult": {
		"_Name": "CreateConfiguration"
	},
	"CreateLinks": [
		{
			"Property": "MachineColors",
			"Target": {
				"EntitySet": "MachineColorsSet",
				"QueryOptions": "$filter=MachineColorsID eq {{#Control:FormCellListPicker1/#SelectedValue}}"
			},
			"_Enabled": true
		},
		{
			"Property": "MachineTyp",
			"Target": {
				"EntitySet": "MachineSet",
				"QueryOptions": "$filter=MachineID eq {{#Control:FormCellSimplePropertyID/#Value}}"
			},
			"_Enabled": true
		},
		{
			"Property": "Order",
			"Target": {
				"EntitySet": "OrderSet",
				"ReadLink": "#ActionResults:CreateOrder/#Property:data/#Property:@odata.readLink"
			},
			"_Enabled": true
		}
	],
	"OnFailure": "/Mahlwerk_Sales/Actions/CreateNewConfigFails.action",
	"OnSuccess": "/Mahlwerk_Sales/Rules/CloseAllPages.js",
	"Properties": {
		"MachineColorsID": "#Control:FormCellListPicker1/#SelectedValue",
		"MachineID": "#Control:FormCellSimplePropertyID/#Value",
		"Pressure": "#Control:FormCellListPicker2/#SelectedValue"
	},
	"Target": {
		"EntitySet": "MachineConfigurationSet",
		"Service": "/Mahlwerk_Sales/Services/Mahlwerk_Sales_MDK.service"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}