{
	"ActionResult": {
		"_Name": "sync"
	},
	"DefiningRequests": [
		{
			"Name": "CustomerSet",
			"Query": "CustomerSet"
		},
		{
			"AutomaticallyRetrievesStreams": true,
			"Name": "MachineSet",
			"Query": "MachineSet"
		},
		{
			"Name": "OrderSet",
			"Query": "OrderSet"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "MachineConfigurationSet",
			"Query": "MachineConfigurationSet"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "TaskSet",
			"Query": "TaskSet"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "AddressSet",
			"Query": "AddressSet"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "OrderEventsSet",
			"Query": "OrderEventsSet"
		},
		{
			"AutomaticallyRetrievesStreams": true,
			"Name": "MachineColorsSet",
			"Query": "MachineColorsSet"
		}
	],
	"OnFailure": "/Mahlwerk_Sales/Actions/Service/SyncFailureMessage.action",
	"Service": "/Mahlwerk_Sales/Services/Mahlwerk_Sales_MDK.service",
	"_Type": "Action.Type.OfflineOData.Download"
}