{
	"OnFailure": "/Mahlwerk_Sales/Actions/Products/ProductImageDownloadFailure.action",
	"Target": {
		"EntitySet": "MachineColorsSet",
		"QueryOptions": "",
		"ReadLink": "/Mahlwerk_Sales/Rules/Product/GetColoredProductReadLink.js",
		"Service": "/Mahlwerk_Sales/Services/Mahlwerk_Sales_MDK.service"
	},
	"_Type": "Action.Type.ODataService.DownloadMedia"
}